In [2]:
import numpy as np

a = np.random.randn(5)

In [3]:
print(a)

[-1.17998258  0.34407122 -0.63858036 -0.89646266 -0.65781879]


In [4]:
print(a.shape) # rank 1 array - Don't use

(5,)


In [5]:
print(a.T)

[-1.17998258  0.34407122 -0.63858036 -0.89646266 -0.65781879]


In [6]:
print(np.dot(a, a.T))

3.1548996442040944


In [7]:
a = np.random.randn(5, 1) # 가급적 이렇게 column vector를 이용해서 신경망 코딩

In [9]:
print(a.T)

[[ 0.595679   -0.13065538  0.34984256  1.36440849 -1.77002261]]


In [10]:
print(np.dot(a, a.T))

[[ 0.35483347 -0.07782867  0.20839387  0.81274949 -1.0543653 ]
 [-0.07782867  0.01707083 -0.04570881 -0.17826731  0.23126298]
 [ 0.20839387 -0.04570881  0.12238982  0.47732816 -0.61922925]
 [ 0.81274949 -0.17826731  0.47732816  1.86161053 -2.41503389]
 [-1.0543653   0.23126298 -0.61922925 -2.41503389  3.13298005]]
